---

- name: Setup systemd for Sui
  hosts: fullnodes
  become: true
  tasks:
  - name: Write sui.service
    template:
      src: sui.service
      dest: /etc/systemd/system/sui.service
      owner: root
      group: root
      force: true

  - name: Enable sui.service
    systemd:
      name: sui.service
      enabled: yes
      daemon_reload: yes