---

- name: Setup Logtail
  hosts: fullnodes
  become: true
  tasks:

  - name: Create Vector config directory
    file:
      path: /etc/vector
      state: directory
      mode: '0755'
      owner: root
      group: root
    tags:
      - logtail

  - name: Download Vector configuration script for apt integration
    get_url:
      url: https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh
      dest: /tmp/bash.deb.sh
      mode: 0755
    tags:
      - logtail

  - name: Run Vector configuraiotn script for apt integration
    shell: /tmp/bash.deb.sh
    tags:
      - logtail

  - name: Add Vector apt preference file
    copy:
      content: |
        Package: vector
        Pin: version 0.28.0-1
        Pin-Priority: 999
      dest: /etc/apt/preferences.d/vector
    tags:
      - logtail

  - name: Download Vector configuration file
    get_url:
      url: https://logtail.com/vector-toml/ubuntu/dRSmTAqrboDVaN8xg4kMpqPv
      dest: /etc/vector/vector.toml
      mode: 0755
    tags:
      - logtail

  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: yes

  - name: Install dependencies
    apt:
      pkg:
      - vector
    tags:
      - logtail

  - name: Refresh systemd
    command: systemctl daemon-reload

  - name: Enable vector.service
    systemd:
      name: vector.service
      enabled: yes

  - name: Start vector via systemd
    systemd:
      name: vector.service
      state: started